services:
  db:
    image: postgres:16
    container_name: mizan-db
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    build: .
    container_name: mizan-odoo
    restart: unless-stopped
    network_mode: host
    depends_on:
      - db
    command: odoo --config=/etc/odoo/odoo.conf
    volumes:
      - ../odoo:/opt/odoo
      - ../custom_addons:/mnt/custom_addons
      - ../third_party/OCA:/mnt/oca_addons
      - ./odoo.conf:/etc/odoo/odoo.conf

volumes:
  postgres_data:
