[options]
admin_passwd = $pbkdf2-sha512$600000$WitFKAUghHBurfV.j7H2ng$hcsNn9zkEHF.6aoCObdkZGgxu1boGBeuhrD7pAgwqlEWZBKDcexBnReN9ILHo.c8h38xfoSOtq80pVQaTouekQ
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /opt/odoo/addons,/mnt/custom_addons,/mnt/oca_addons
data_dir = /var/lib/odoo
proxy_mode = True
log_level = info

